name: Building and Pushed
on:
  schedule:
       - cron: "0 0 * * *"   
  push:
    branches:
      - master
    paths:
      - Dockerfile
      - .github/workflows/main.yml

jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Determine tag
        run: | 
          cd /tmp
          git -c http.sslVerify=false clone https://github.com/drone/drone.git
          cd drone
          export TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          export TAG=${TAG:1}
          echo "TAG=$TAG" >> $GITHUB_ENV
          
      - name: Check $TAG
        run: echo $TAG
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push   
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile  
          push: true
          tags: nemonik/drone:latest, nemonik/drone:${{ env.TAG }}
